// AUTO-GENERATED by scripts/generate-clouds-lookup.mjs — do not edit
// Source: data/fire-feasibility/clouds-generation-b.xlsx (sheet: Sheet 1)

import type { CloudsFeasibilityLookupData } from './cloudsFeasibility.types.ts'

export const CLOUDS_FEASIBILITY_GEN_B_LOOKUP_GENERATED_AT = "2026-05-27T17:58:02.619Z"

export const cloudsFeasibilityGenBLookupData: CloudsFeasibilityLookupData = 
{
  "heightBands": [
    {
      "id": "h_900_1000",
      "min": 900,
      "max": 1000,
      "label": "900-1000"
    },
    {
      "id": "h_800_900",
      "min": 800,
      "max": 900,
      "label": "800-900"
    },
    {
      "id": "h_700_800",
      "min": 700,
      "max": 800,
      "label": "700-800"
    },
    {
      "id": "h_600_700",
      "min": 600,
      "max": 700,
      "label": "600-700"
    },
    {
      "id": "h_500_600",
      "min": 500,
      "max": 600,
      "label": "500-600"
    },
    {
      "id": "h_400_500",
      "min": 400,
      "max": 500,
      "label": "400-500"
    },
    {
      "id": "h_300_400",
      "min": 300,
      "max": 400,
      "label": "300-400"
    },
    {
      "id": "h_200_300",
      "min": 200,
      "max": 300,
      "label": "200-300"
    },
    {
      "id": "h_100_200",
      "min": 100,
      "max": 200,
      "label": "100-200"
    },
    {
      "id": "h_0_100",
      "min": 0,
      "max": 100,
      "label": "0-100"
    },
    {
      "id": "h_-100_0",
      "min": -100,
      "max": 0,
      "label": "-100-0"
    },
    {
      "id": "h_-200_-100",
      "min": -200,
      "max": -100,
      "label": "-100 - -200"
    },
    {
      "id": "h_-300_-200",
      "min": -300,
      "max": -200,
      "label": "-200 - -300"
    },
    {
      "id": "h_-400_-300",
      "min": -400,
      "max": -300,
      "label": "-300 - -400"
    },
    {
      "id": "h_-500_-400",
      "min": -500,
      "max": -400,
      "label": "-400 - -500"
    },
    {
      "id": "h_-600_-500",
      "min": -600,
      "max": -500,
      "label": "-500 - -600"
    },
    {
      "id": "h_-700_-600",
      "min": -700,
      "max": -600,
      "label": "-600 - -700"
    },
    {
      "id": "h_-800_-700",
      "min": -800,
      "max": -700,
      "label": "-700 - -800"
    },
    {
      "id": "h_-900_-800",
      "min": -900,
      "max": -800,
      "label": "-800 - -900"
    },
    {
      "id": "h_-1000_-900",
      "min": -1000,
      "max": -900,
      "label": "-900 - -1000"
    }
  ],
  "rangeBands": [
    {
      "id": "r_4000_5000",
      "min": 4000,
      "max": 5000,
      "label": "4-5"
    },
    {
      "id": "r_5000_6000",
      "min": 5000,
      "max": 6000,
      "label": "5-6"
    },
    {
      "id": "r_6000_7000",
      "min": 6000,
      "max": 7000,
      "label": "6-7"
    },
    {
      "id": "r_7000_8000",
      "min": 7000,
      "max": 8000,
      "label": "7-8"
    },
    {
      "id": "r_8000_9000",
      "min": 8000,
      "max": 9000,
      "label": "8-9"
    },
    {
      "id": "r_9000_9750",
      "min": 9000,
      "max": 9750,
      "label": "9-9.75"
    }
  ],
  "lookup": {
    "h_900_1000|r_5000_6000": {
      "loftedPlus": 40,
      "lofted": 40
    },
    "h_900_1000|r_6000_7000": {
      "loftedPlus": 260,
      "lofted": 210
    },
    "h_900_1000|r_7000_8000": {
      "loftedPlus": 480,
      "lofted": 460
    },
    "h_900_1000|r_8000_9000": {
      "loftedPlus": 520,
      "lofted": 500
    },
    "h_900_1000|r_9000_9750": {
      "loftedPlus": 860,
      "lofted": 780
    },
    "h_800_900|r_5000_6000": {
      "loftedPlus": 80,
      "lofted": 80
    },
    "h_800_900|r_6000_7000": {
      "loftedPlus": 310,
      "lofted": 260
    },
    "h_800_900|r_7000_8000": {
      "loftedPlus": 520,
      "lofted": 490
    },
    "h_800_900|r_8000_9000": {
      "loftedPlus": 560,
      "lofted": 540
    },
    "h_800_900|r_9000_9750": {
      "loftedPlus": 910,
      "lofted": 800
    },
    "h_700_800|r_5000_6000": {
      "loftedPlus": 130,
      "lofted": 130
    },
    "h_700_800|r_6000_7000": {
      "loftedPlus": 350,
      "lofted": 310
    },
    "h_700_800|r_7000_8000": {
      "loftedPlus": 560,
      "lofted": 530
    },
    "h_700_800|r_8000_9000": {
      "loftedPlus": 600,
      "lofted": 590
    },
    "h_700_800|r_9000_9750": {
      "loftedPlus": 970,
      "lofted": 830
    },
    "h_600_700|r_5000_6000": {
      "loftedPlus": 170,
      "lofted": 170
    },
    "h_600_700|r_6000_7000": {
      "loftedPlus": 400,
      "lofted": 350
    },
    "h_600_700|r_7000_8000": {
      "loftedPlus": 600,
      "lofted": 570
    },
    "h_600_700|r_8000_9000": {
      "loftedPlus": 650,
      "lofted": 630
    },
    "h_600_700|r_9000_9750": {
      "loftedPlus": 1020,
      "lofted": 850,
      "low": 160
    },
    "h_500_600|r_5000_6000": {
      "loftedPlus": 220,
      "lofted": 220
    },
    "h_500_600|r_6000_7000": {
      "loftedPlus": 440,
      "lofted": 400
    },
    "h_500_600|r_7000_8000": {
      "loftedPlus": 640,
      "lofted": 620,
      "low": 70
    },
    "h_500_600|r_8000_9000": {
      "loftedPlus": 700,
      "lofted": 670
    },
    "h_500_600|r_9000_9750": {
      "loftedPlus": 1070,
      "lofted": 850,
      "low": 200
    },
    "h_400_500|r_5000_6000": {
      "loftedPlus": 270,
      "lofted": 270
    },
    "h_400_500|r_6000_7000": {
      "loftedPlus": 490,
      "lofted": 450,
      "low": 70
    },
    "h_400_500|r_7000_8000": {
      "loftedPlus": 680,
      "lofted": 680,
      "low": 110
    },
    "h_400_500|r_8000_9000": {
      "loftedPlus": 750,
      "lofted": 700,
      "low": 120
    },
    "h_400_500|r_9000_9750": {
      "loftedPlus": 1110,
      "lofted": 850,
      "low": 260
    },
    "h_300_400|r_5000_6000": {
      "loftedPlus": 310,
      "lofted": 310,
      "low": 70
    },
    "h_300_400|r_6000_7000": {
      "loftedPlus": 540,
      "lofted": 500,
      "low": 120
    },
    "h_300_400|r_7000_8000": {
      "loftedPlus": 720,
      "lofted": 600,
      "low": 160
    },
    "h_300_400|r_8000_9000": {
      "loftedPlus": 800,
      "lofted": 710,
      "low": 170
    },
    "h_300_400|r_9000_9750": {
      "loftedPlus": 1150,
      "lofted": 850,
      "low": 300
    },
    "h_200_300|r_4000_5000": {
      "lofted": 60
    },
    "h_200_300|r_5000_6000": {
      "loftedPlus": 360,
      "lofted": 360,
      "low": 110
    },
    "h_200_300|r_6000_7000": {
      "loftedPlus": 590,
      "lofted": 540,
      "low": 170
    },
    "h_200_300|r_7000_8000": {
      "loftedPlus": 750,
      "lofted": 710,
      "low": 200
    },
    "h_200_300|r_8000_9000": {
      "loftedPlus": 850,
      "lofted": 720,
      "low": 210
    },
    "h_200_300|r_9000_9750": {
      "loftedPlus": 1180,
      "lofted": 840,
      "low": 360
    },
    "h_100_200|r_4000_5000": {
      "loftedPlus": 90,
      "lofted": 110,
      "low": 100
    },
    "h_100_200|r_5000_6000": {
      "loftedPlus": 410,
      "lofted": 410,
      "low": 160
    },
    "h_100_200|r_6000_7000": {
      "loftedPlus": 640,
      "lofted": 590,
      "low": 220
    },
    "h_100_200|r_7000_8000": {
      "loftedPlus": 800,
      "lofted": 720,
      "low": 240
    },
    "h_100_200|r_8000_9000": {
      "loftedPlus": 890,
      "lofted": 710,
      "low": 270
    },
    "h_100_200|r_9000_9750": {
      "loftedPlus": 1220,
      "lofted": 830,
      "low": 390
    },
    "h_0_100|r_4000_5000": {
      "loftedPlus": 150,
      "lofted": 180,
      "low": 160
    },
    "h_0_100|r_5000_6000": {
      "loftedPlus": 460,
      "lofted": 460,
      "low": 220
    },
    "h_0_100|r_6000_7000": {
      "loftedPlus": 690,
      "lofted": 650,
      "low": 260
    },
    "h_0_100|r_7000_8000": {
      "loftedPlus": 840,
      "lofted": 720,
      "low": 290
    },
    "h_0_100|r_8000_9000": {
      "loftedPlus": 940,
      "lofted": 710,
      "low": 320
    },
    "h_0_100|r_9000_9750": {
      "loftedPlus": 1250,
      "lofted": 800,
      "low": 450
    },
    "h_-100_0|r_4000_5000": {
      "loftedPlus": 210,
      "lofted": 240,
      "low": 220
    },
    "h_-100_0|r_5000_6000": {
      "loftedPlus": 510,
      "lofted": 510,
      "low": 250
    },
    "h_-100_0|r_6000_7000": {
      "loftedPlus": 740,
      "lofted": 580,
      "low": 320
    },
    "h_-100_0|r_7000_8000": {
      "loftedPlus": 880,
      "lofted": 710,
      "low": 330
    },
    "h_-100_0|r_8000_9000": {
      "loftedPlus": 990,
      "lofted": 690,
      "low": 370
    },
    "h_-100_0|r_9000_9750": {
      "loftedPlus": 1280,
      "lofted": 780,
      "low": 490
    },
    "h_-200_-100|r_4000_5000": {
      "loftedPlus": 280,
      "lofted": 300,
      "low": 280
    },
    "h_-200_-100|r_5000_6000": {
      "loftedPlus": 560,
      "lofted": 560,
      "low": 300
    },
    "h_-200_-100|r_6000_7000": {
      "loftedPlus": 790,
      "lofted": 670,
      "low": 370
    },
    "h_-200_-100|r_7000_8000": {
      "loftedPlus": 900,
      "lofted": 690,
      "low": 380
    },
    "h_-200_-100|r_8000_9000": {
      "loftedPlus": 1040,
      "lofted": 660,
      "low": 420
    },
    "h_-200_-100|r_9000_9750": {
      "loftedPlus": 1300,
      "lofted": 750,
      "low": 480
    },
    "h_-300_-200|r_4000_5000": {
      "loftedPlus": 340,
      "lofted": 360,
      "low": 340
    },
    "h_-300_-200|r_5000_6000": {
      "loftedPlus": 560,
      "lofted": 610,
      "low": 350
    },
    "h_-300_-200|r_6000_7000": {
      "loftedPlus": 840,
      "lofted": 650,
      "low": 400
    },
    "h_-300_-200|r_7000_8000": {
      "loftedPlus": 950,
      "lofted": 640,
      "low": 380
    },
    "h_-300_-200|r_8000_9000": {
      "loftedPlus": 1080,
      "lofted": 620,
      "low": 440
    },
    "h_-300_-200|r_9000_9750": {
      "loftedPlus": 1330,
      "lofted": 730,
      "low": 490
    },
    "h_-400_-300|r_4000_5000": {
      "loftedPlus": 400,
      "lofted": 430,
      "low": 400
    },
    "h_-400_-300|r_5000_6000": {
      "loftedPlus": 520,
      "lofted": 520,
      "low": 380
    },
    "h_-400_-300|r_6000_7000": {
      "loftedPlus": 890,
      "lofted": 590,
      "low": 430
    },
    "h_-400_-300|r_7000_8000": {
      "loftedPlus": 990,
      "lofted": 590,
      "low": 400
    },
    "h_-400_-300|r_8000_9000": {
      "loftedPlus": 1110,
      "lofted": 560,
      "low": 460
    },
    "h_-400_-300|r_9000_9750": {
      "loftedPlus": 1350,
      "lofted": 660,
      "low": 520
    },
    "h_-500_-400|r_4000_5000": {
      "loftedPlus": 440,
      "lofted": 460,
      "low": 460
    },
    "h_-500_-400|r_5000_6000": {
      "loftedPlus": 470,
      "lofted": 500,
      "low": 420
    },
    "h_-500_-400|r_6000_7000": {
      "loftedPlus": 890,
      "lofted": 530,
      "low": 470
    },
    "h_-500_-400|r_7000_8000": {
      "loftedPlus": 990,
      "lofted": 510,
      "low": 430
    },
    "h_-500_-400|r_8000_9000": {
      "loftedPlus": 1130,
      "lofted": 490,
      "low": 490
    },
    "h_-500_-400|r_9000_9750": {
      "loftedPlus": 1370,
      "lofted": 620,
      "low": 520
    },
    "h_-600_-500|r_4000_5000": {
      "loftedPlus": 480,
      "lofted": 490,
      "low": 520
    },
    "h_-600_-500|r_5000_6000": {
      "loftedPlus": 480,
      "lofted": 490,
      "low": 470
    },
    "h_-600_-500|r_6000_7000": {
      "loftedPlus": 850,
      "lofted": 570,
      "low": 500
    },
    "h_-600_-500|r_7000_8000": {
      "loftedPlus": 960,
      "lofted": 560,
      "low": 540
    },
    "h_-600_-500|r_8000_9000": {
      "loftedPlus": 1150,
      "lofted": 540,
      "low": 530
    },
    "h_-600_-500|r_9000_9750": {
      "loftedPlus": 1380,
      "lofted": 620,
      "low": 540
    },
    "h_-700_-600|r_4000_5000": {
      "loftedPlus": 540,
      "lofted": 550,
      "low": 580
    },
    "h_-700_-600|r_5000_6000": {
      "loftedPlus": 600,
      "lofted": 580,
      "low": 510
    },
    "h_-700_-600|r_6000_7000": {
      "loftedPlus": 890,
      "lofted": 620,
      "low": 550
    },
    "h_-700_-600|r_7000_8000": {
      "loftedPlus": 910,
      "lofted": 560,
      "low": 670
    },
    "h_-700_-600|r_8000_9000": {
      "loftedPlus": 1160,
      "lofted": 560,
      "low": 540
    },
    "h_-700_-600|r_9000_9750": {
      "loftedPlus": 1390,
      "lofted": 650,
      "low": 560
    },
    "h_-800_-700|r_4000_5000": {
      "loftedPlus": 610,
      "lofted": 610,
      "low": 640
    },
    "h_-800_-700|r_5000_6000": {
      "loftedPlus": 650,
      "lofted": 600,
      "low": 560
    },
    "h_-800_-700|r_6000_7000": {
      "loftedPlus": 870,
      "lofted": 630,
      "low": 630
    },
    "h_-800_-700|r_7000_8000": {
      "loftedPlus": 820,
      "lofted": 610,
      "low": 710
    },
    "h_-800_-700|r_8000_9000": {
      "loftedPlus": 1170,
      "lofted": 610,
      "low": 580
    },
    "h_-800_-700|r_9000_9750": {
      "loftedPlus": 1390,
      "lofted": 660,
      "low": 570
    },
    "h_-900_-800|r_4000_5000": {
      "loftedPlus": 670,
      "lofted": 670,
      "low": 700
    },
    "h_-900_-800|r_5000_6000": {
      "loftedPlus": 720,
      "lofted": 680,
      "low": 600
    },
    "h_-900_-800|r_6000_7000": {
      "loftedPlus": 760,
      "lofted": 680,
      "low": 680
    },
    "h_-900_-800|r_7000_8000": {
      "loftedPlus": 710,
      "lofted": 640,
      "low": 730
    },
    "h_-900_-800|r_8000_9000": {
      "loftedPlus": 1160,
      "lofted": 630,
      "low": 600
    },
    "h_-900_-800|r_9000_9750": {
      "loftedPlus": 1390,
      "lofted": 680,
      "low": 590
    },
    "h_-1000_-900|r_4000_5000": {
      "loftedPlus": 730,
      "lofted": 730,
      "low": 760
    },
    "h_-1000_-900|r_5000_6000": {
      "loftedPlus": 770,
      "lofted": 680,
      "low": 630
    },
    "h_-1000_-900|r_6000_7000": {
      "loftedPlus": 770,
      "lofted": 710,
      "low": 710
    },
    "h_-1000_-900|r_7000_8000": {
      "loftedPlus": 730,
      "lofted": 780,
      "low": 750
    },
    "h_-1000_-900|r_8000_9000": {
      "loftedPlus": 1150,
      "lofted": 660,
      "low": 620
    },
    "h_-1000_-900|r_9000_9750": {
      "loftedPlus": 1380,
      "lofted": 690,
      "low": 590
    }
  }
}
