import type { FormSchema } from '../domain/dynamicForm.types'

export const missChecklistFormSchema: FormSchema = {
  fields: [
    { type: 'header', text: 'מול מציין', bold: true },

    {
      type: 'toggle',
      key: 'weatherHitNearTarget',
      label: 'האם ווודאו תנאי מזג האוויר בקרבת המטרה ולפניה (עננות? רוח? גשם?)?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'weatherConditionsChecked',
      label: 'האם תנאי מזג האוויר וודאו בגבהים שונים של מעוף הטיל?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'positionVerifiedWithIndicator',
      label: 'האם נעשה אימות נוסף מול המציין של נתוני העמדה (זווית קודקוד) והמטרה?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'concealmentNearTarget',
      label: 'האם היו הסתרים בקרבת המטרה? האם נעשה ווידוא שאין הסתרים גבולים?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'concealmentInMissileDirection',
      label: 'בירי כיווני האם היה הסתר בכיוון הגעת הטיל? (לא בהכרח בקו עמדה מטרה)',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'kozVideoTaken',
      label: 'האם הייתה ווידוא של הקו"צ?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    { type: 'text', key: 'targetType', label: 'מה היה סוג המטרה?' },
    {
      type: 'toggle',
      key: 'reflectiveTarget',
      label: 'האם המטרה הייתה רפלקטיבית או בקרבת משטחים רפלקטיביים?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    { type: 'text', key: 'targetFace', label: 'מה היה מפנה המטרה? (חזית וכיוון החזית? גג?)' },
    {
      type: 'toggle',
      key: 'multipleSpots',
      label: 'האם היה ריבוי כתמים?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'spotBounced',
      label: 'האם בוצעה הקפצת כתם?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'deflectionDone',
      label: 'האם הייתה הסטה?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    { type: 'text', key: 'crossPosition', label: 'מה מיקום הצלב ביחס לנקודת הפגיעה הרצויה?' },
    { type: 'text', key: 'missileImpactRelativeToCross', label: 'היכן פגע הטיל ביחס לצלב?' },
    {
      type: 'toggle',
      key: 'spotSliding',
      label: 'האם הייתה גלישה של הכתם (גלישה מהחזית? גלישה לתוך חלון? וכו\')?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'spotDrift',
      label: 'האם הייתה בליעה של הכתם?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },

    { type: 'header', text: 'שיגור', bold: true },

    {
      type: 'toggle',
      key: 'hitDetected',
      label: 'האם זוהתה פגיעה?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'missileExploded',
      label: 'האם הטיל התפוצץ? (אי-פיצוץ יכול להעיד על בעיה ברכישת הכתם)',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    { type: 'number', key: 'impactDistanceMeters', label: 'באיזה מרחק מ-נ.צ. המטרה זוהתה פגיעת הטיל? (מטרים)' },
    {
      type: 'toggle',
      key: 'malfunctionOnExit',
      label: 'האם זוהתה תקלה בעת יציאת הטיל? (טיפוס תקין? זווית יציאה תקינה? כיוון מעוף תקין?)',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'dataValidated',
      label: 'האם נעשה ווידוא לתקינות הנתונים?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'allMissionsValidated',
      label: 'האם נעשה ווידוא לכפל מטרות או משימות בעלות אותו השם?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'northSourceMethod',
      label: 'כיצד הוזנה האק"א?',
      options: ['מוצא צפון', 'מצפן סימאפס'],
      defaultValue: 'מוצא צפון',
    },
    {
      type: 'toggle',
      key: 'northSourceValidated',
      label: 'האם נעשה ווידוא נוסף של האק"א?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'fallingIndicatorsOk',
      label: 'האם בהוצאת הטילים מהמזוודות מצייני הנפילה היו תקינים?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'hiveOk',
      label: 'האם הכוורת תקינה (פרפרים סגורות? חנוכיות תקניות? מחברים תקינים? הכוורת לא מעוקמת? ראצ\'טים משוחררים? סגר מסע פתוח?)',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },

    {
      type: 'toggle',
      key: 'directionCodeInsertedIn',
      label: 'האם קוד הציוון הוכנס במשימת ירי או במציין?',
      options: ["הוכנס במשימת יר'", "הוכנס המצי'"],
      defaultValue: "הוכנס במשימת יר'",
    },
    {
      type: 'toggle',
      key: 'targetAbove8km',
      label: 'אם היה שימוש בכיוונות המטרה הייתה מעל 8 ק"מ +?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
    {
      type: 'toggle',
      key: 'directionApproval',
      label: 'האם היה אישור מהתא עבור כיוונות?',
      options: ['כן', 'לא'],
      defaultValue: 'לא',
    },
  ],
}
