/**
 * Dev-only utility: writes the same mock data that scripts/seed-localStorage.mjs
 * embeds into public/dev-seed.html directly into the current localStorage.
 *
 * Must stay in sync with scripts/seed-localStorage.mjs whenever seed data changes.
 *
 * Keys include userNotes, bachs, missChecklists (see src/storage/).
 */

const savedAt = '2026-05-10T10:00:00.000Z'

const IDS = {
  posAlpha: 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaa1',
  posBravo: 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaa2',
  posCharlie: 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaa3',
  target1: 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbb1',
  target2: 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbb2',
  target3: 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbb3',
  ind1: 'cccccccc-cccc-4ccc-cccc-ccccccccccc1',
  ind2: 'cccccccc-cccc-4ccc-cccc-ccccccccccc2',
  log1: 'dddddddd-dddd-4ddd-dddd-dddddddddddd1',
  log2: 'dddddddd-dddd-4ddd-dddd-dddddddddddd2',
  note1: 'eeeeeeee-eeee-4eee-eeee-eeeeeeeeeee1',
  note2: 'eeeeeeee-eeee-4eee-eeee-eeeeeeeeeee2',
  bach1: 'ffffffff-ffff-4fff-ffff-fffffffffff1',
  bach2: 'ffffffff-ffff-4fff-ffff-fffffffffff2',
  missChecklist1: 'gggggggg-gggg-4ggg-gggg-ggggggggggg1',
}

const positions = [
  {
    id: IDS.posAlpha,
    savedAt,
    stationName: 'עמדה אלפא',
    coordinates: { east: '345678', north: '3456789', palach: '36' },
    altitude: 420,
    aka: 40,
    launcherType: 'vehicle',
    vehicleId: 'רכב-12',
    pitch: 1.1,
    roll: 0.2,
  },
  {
    id: IDS.posBravo,
    savedAt,
    stationName: 'עמדה בראבו',
    coordinates: { east: '456789', north: '4567890', palach: '36' },
    altitude: 380,
  },
  {
    id: IDS.posCharlie,
    savedAt,
    stationName: 'עמדה צ׳ארלי',
    coordinates: { east: '567890', north: '5678901', palach: '36' },
    altitude: 510,
  },
]

const targets = [
  {
    id: IDS.target1,
    targetName: 'יעד דמה א׳',
    targetDescription: 'מטרה לאימון',
    coordinates: { east: '400000', north: '4000000', palach: '36' },
    altitude: 440,
  },
  {
    id: IDS.target2,
    targetName: 'יעד דמה ב׳',
    coordinates: { east: '410000', north: '4100000', palach: '36' },
    altitude: 395,
  },
  {
    id: IDS.target3,
    targetName: 'יעד דמה ג׳',
    targetDescription: 'מבנה',
    coordinates: { east: '420000', north: '4200000', palach: '36' },
    altitude: 480,
  },
]

const indicators = [
  {
    id: IDS.ind1,
    savedAt,
    indicatorName: 'מציין דמה א׳',
    coordinates: { east: '401234', north: '4012345', palach: '36' },
    altitude: 430,
    means: 'שיח',
    markCode: 12,
    targetDomain: 'צפון',
  },
  {
    id: IDS.ind2,
    savedAt,
    indicatorName: 'מציין דמה ב׳',
    coordinates: { east: '402567', north: '4025678', palach: '36' },
    altitude: 400,
    means: 'ראטלר',
    markCode: 7,
  },
]

const attackLogs = [
  {
    id: IDS.log1,
    savedAt,
    targetName: 'יעד דמה א׳',
    date: '2026-05-09',
    wasAttacked: 'yes',
    hit: true,
    result: 'פגיעה טובה',
    time: '14:30',
    launcherType: 'רכבי',
    generation: 'a',
    stationTargetRange: 8500,
    stationTargetAzimuth: 1200,
  },
  {
    id: IDS.log2,
    savedAt,
    targetName: 'יעד דמה ב׳',
    date: '2026-05-08',
    wasAttacked: 'no',
    hit: false,
    generation: 'b',
  },
]

const userNotes = [
  {
    id: IDS.note1,
    text: 'הערת דמה: לבדיקת רשימת ההערות במסך.',
    createdAtIso: '2026-05-10T08:15:00.000Z',
    updatedAtIso: '2026-05-10T09:00:00.000Z',
  },
  {
    id: IDS.note2,
    text: 'הערה שנייה ללא עריכה.',
    createdAtIso: '2026-05-09T16:45:00.000Z',
  },
]

const bachs = [
  {
    id: IDS.bach1,
    createdAt: 1746784800000,
    values: {
      date: '2026-05-09',
      hour: '14:00',
      sector: 'גזרה צפון',
      launchingUnit: 'חוליה 1',
      markingUnit: 'חוליה מציין א׳',
      targetId: IDS.target1,
      targetName: 'יעד דמה א׳',
      detection: 'אופטי',
      targetCoords: { east: '400000', north: '4000000', palach: '36' },
      targetAltitude: '440',
      targetType: 'מבנה',
      targetDescription: 'מטרה לאימון',
      requiredAchievement: 'פגיעה',
      markingFactor: 'מציין א׳',
      recordingFactor: 'קצין תצפית',
      flightAltitude: '500',
      hitProbability: 'בינוני',
      hitProbabilityDetails: 'מטרה חצי מוסתרת',
      controlApproved: 'כן',
      approvedBy: 'מ"פ',
      positionName: 'עמדה אלפא',
      positionCoords: { east: '345678', north: '3456789', palach: '36' },
      positionAltitude: '420',
      missileC: 'א',
      serialNumber: '12345',
      barrelNumber: '1',
      koz: '1200',
      aka: '40',
      wind: '5 קמ"ש צפון',
      clouds: '3/8',
      azimuthToTarget: '1200',
      launchRange: '8500',
      flightType: 'flat',
      impact: 'ימין',
      arcTrack: 'לא',
      arcTrackDetails: '',
      fuseType: 'T-433',
      delay: 'לא',
      launchTime: '14:30',
      missileFlightTime: '12',
      munitionsCount: '1',
      manualPlacement: 'לא',
      elevationComputed: '45.2',
      elevationActual: '45.2',
      sizeupComputed: '1200',
      sizeupActual: '1200',
      powerSource: 'רכב מונע',
      rightSectorAzimuth: '1400',
      leftSectorAzimuth: '1000',
      indicatorId: IDS.ind1,
      indicatorName: 'מציין דמה א׳',
      indicatorPositionCoords: { east: '401234', north: '4012345', palach: '36' },
      indicatorAltitude: '430',
      observationMeans: 'אופטי',
      indicatorMeans: 'שיח',
      indicatorKoz: '12',
      indicatorToTargetAzimuth: '1180',
      indicatorWind: '4 קמ"ש',
      indicatorClouds: '2/8',
      deviationDirection: 'ימינה',
      aimPoint: 'מרכז המבנה',
      indicationRange: '850',
      spotSize: 'קטן',
      targetSize: 'בינוני',
      concealments: 'אין',
      bdaResult: 'אלפא',
      bdaWithObserver: 'פגיעה טובה, השמדה מלאה',
      unusualEvents: 'אין',
      results: 'הושמד',
      renewed: 'לא רלוונטי',
      readyTime: '15:00',
      malfunctions: 'אין',
    },
  },
  {
    id: IDS.bach2,
    createdAt: 1746698400000,
    values: {
      date: '2026-05-08',
      hour: '09:30',
      sector: 'גזרה דרום',
      launchingUnit: 'חוליה 2',
      markingUnit: 'חוליה מציין ב׳',
      targetName: 'יעד דמה ב׳',
      detection: 'מכ"ם',
      targetCoords: { east: '410000', north: '4100000', palach: '36' },
      targetAltitude: '395',
      targetType: 'רכב',
      requiredAchievement: 'נטרול',
      flightAltitude: '400',
      hitProbability: 'קשה',
      hitProbabilityDetails: 'מטרה נעה',
      controlApproved: 'לא',
      positionName: 'עמדה בראבו',
      positionCoords: { east: '456789', north: '4567890', palach: '36' },
      positionAltitude: '380',
      barrelNumber: '2',
      koz: '0800',
      aka: '38',
      wind: '10 קמ"ש מזרח',
      clouds: '5/8',
      azimuthToTarget: '0800',
      launchRange: '6200',
      flightType: 'lofted',
      impact: 'למטה',
      arcTrack: 'כן',
      arcTrackDirection: 'שמאל',
      delay: 'קצרה',
      launchTime: '09:45',
      munitionsCount: '2',
      manualPlacement: 'כן',
      elevationComputed: '38.0',
      elevationActual: '38.5',
      powerSource: 'גנרטור',
      bdaResult: 'ברבו',
      unusualEvents: 'ריח חריג קל בשיגור',
      results: 'פגיעה חלקית',
      malfunctions: 'תקלת תקשורת קצרה לפני ירי',
    },
  },
]

const missChecklists = [
  {
    id: IDS.missChecklist1,
    createdAt: 1746698400000,
    values: {
      weatherHitNearTarget: 'כן',
      weatherConditionsChecked: 'כן',
      positionVerifiedWithIndicator: 'כן',
      concealmentNearTarget: 'כן',
      concealmentInMissileDirection: 'לא',
      kozVideoTaken: 'כן',
      targetType: 'מבנה',
      reflectiveTarget: 'לא',
      targetFace: 'חזית דרום',
      multipleSpots: 'לא',
      spotBounced: 'לא',
      deflectionDone: 'לא',
      crossPosition: 'מרכז',
      missileImpactRelativeToCross: '3 מטר ימינה',
      spotSliding: 'לא',
      spotDrift: 'לא',
      hitDetected: 'לא',
      missileExploded: 'כן',
      impactDistanceMeters: 3,
      malfunctionOnExit: 'לא',
      dataValidated: 'כן',
      allMissionsValidated: 'כן',
      northSourceMethod: 'מוצא צפון',
      northSourceValidated: 'כן',
      fallingIndicatorsOk: 'כן',
      hiveOk: 'כן',
      directionCodeInsertedIn: "הוכנס במשימת יר'",
      targetAbove8km: 'לא',
      directionApproval: 'לא',
    },
  },
]

const SEED_PAYLOAD: Record<string, string> = {
  positions: JSON.stringify(positions),
  currentPositionId: IDS.posAlpha,
  referencePositionId: IDS.posBravo,
  targets: JSON.stringify(targets),
  indicators: JSON.stringify(indicators),
  attackLogs: JSON.stringify(attackLogs),
  userNotes: JSON.stringify(userNotes),
  bachs: JSON.stringify(bachs),
  missChecklists: JSON.stringify(missChecklists),
}

export function applySeedMockData(): void {
  for (const [key, value] of Object.entries(SEED_PAYLOAD)) {
    localStorage.setItem(key, value)
  }
}
